version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building Strapi..."
      - npm run build  

  post_build:
    commands:
      - echo "Preparing deploy directory..."
      - mkdir -p deploy
      - rsync -av --progress --exclude=deploy ./ deploy
      - echo "Build ready for deployment."

artifacts:
  files:
    - "**/*"
  base-directory: "deploy"
